namespace:
  name: prod
 
image:
  repository: nginx
  tag: 1.17.0

replicaCount: 2

resources:
  limits:
    memory: "256Mi"
    cpu: "70m"

service:
  port: 80

configMap:
  data:
    version: 1.17.0